#!/bin/bash

#SBATCH --partition=rome
#SBATCH --job-name=Debug_MultiAgent
#SBATCH --ntasks=120
#SBATCH --cpus-per-task=1
#SBATCH --time=05:00:00
#SBATCH --output=/home/schatterji1/Debug_MultiAgent/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate pls

cd $HOME/ShieldedMARL/pettingzoo

srun -n 5 python main.py --config=configs/ma_msh/msh2/IPPO_2.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/IPPO_3.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/IPPO_4.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/IPPO_5.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/MAPPO_2.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/MAPPO_3.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/MAPPO_4.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/MAPPO_5.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/ACSPPO_2.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/ACSPPO_3.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/ACSPPO_4.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/ACSPPO_5.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SIPPO_2.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SIPPO_3.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SIPPO_4.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SIPPO_5.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SMAPPO_2.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SMAPPO_3.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SMAPPO_4.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SMAPPO_5.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SACSPPO_2.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SACSPPO_3.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SACSPPO_4.json &
srun -n 5 python main.py --config=configs/ma_msh/msh2/SACSPPO_5.json