#!/bin/bash

#SBATCH --partition=rome
#SBATCH --job-name=Debug_MultiAgent
#SBATCH --ntasks=128
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --output=/home/schatterji1/Debug_MultiAgent/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate pls

cd $HOME/ShieldedMARL/pettingzoo

srun -n 128 wandb agent --count 1 satchat/snellius_base_debug_posix_markov_stag_hunt/q2fp9g7m

