#!/bin/bash

#SBATCH --partition=genoa
#SBATCH --job-name=Debug_MultiAgent
#SBATCH --ntasks=90
#SBATCH --cpus-per-task=2
#SBATCH --time=03:00:00
#SBATCH --output=/home/schatterji1/Debug_MultiAgent/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate pls

cd $HOME/ShieldedMARL/pettingzoo

srun -n 5 python main.py --config=configs/ma_msh/msh1/SIPPO_00.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SIPPO_02.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SIPPO_04.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SIPPO_06.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SIPPO_08.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SIPPO_10.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SMAPPO_00.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SMAPPO_02.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SMAPPO_04.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SMAPPO_06.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SMAPPO_08.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SMAPPO_10.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SACSPPO_00.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SACSPPO_02.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SACSPPO_04.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SACSPPO_06.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SACSPPO_08.json &
srun -n 5 python main.py --config=configs/ma_msh/msh1/SACSPPO_10.json